Uniswap/widgets

src/utils/formatCurrencyAmount.ts

minor fix — very small fees were previously rendering as "<0"
before:
after:
now renders as "<0.00001"

fix: very small integrator fee in swap details should render more decimals

---

src/components/Swap/SwapButton/index.tsx

before: (wrap button stays in spinning state even after user rejects tx)
after:

fix: set isPending false if wrap tx errors

---

src/components/ActionButton.tsx
src/components/Button.tsx
src/utils/formatCurrencyAmount.ts

currently the disabled swap button appears transparent. we want to switch from using an outline -> a 40% opacity button, as per integrator request
before:
after:

fix: change disabled state swap button opacity

---

src/components/Expando.tsx

Previously, only the arrow button was clickable to open swap details. Now, this entire row is clickable:

fix: make swap details row clickable

---

src/components/TokenSelect/TokenOptions.tsx

Previously, token dropdown only used 2 sigfigs (i.e. token balance of 1234 would get displayed as 1200)
Use 4 sigfigs to standardize with interface.

fix: token dropdown balances should use 4 sigfigs

---

src/components/Button.tsx
src/components/Dialog.tsx
src/components/TokenSelect/TokenButton.tsx
src/components/Widget.tsx
src/icons/index.tsx

We use an X icon to close dialog tabs, which creates a double X when the widget is hosted in an integrator modal.
* change X to a back arrow
* change animation from vertical to horizontal slide
Previously:
Now:

fix: use back button instead of X

---

src/hooks/routing/clientSideSmartOrderRouter.ts
src/hooks/routing/useRouterArguments.ts
src/hooks/routing/useRouterTrade.ts
src/state/index.tsx
src/state/routing/slice.ts

Instead of reinstantiating provider obj from providerUrl, we want to pass in our existing JsonRpcProvider obj to routingApi. While rtk-query will cache args, it doesn't destroy the provider args - meaning our javascript garbage collector will collect it, which mean it may live in memory for longer than we want. (??)
Since we don't need time-travel debugging nor persistence, we can store non-serializable objects in state.
* We turn off the serializable check for routing
* Use a custom `serializeQueryArgs` fxn to generate a query cache key

fix: clientside router should use existing JsonRpcProvider obj

---

src/components/TokenSelect/TokenButton.tsx

Nit from Phil - chevron stroke should be 2px, not 3px

fix: stroke width of token button chevron to 2px

---

src/components/Swap/RoutingDiagram/index.tsx

remove tooltip hops description - confusing language + we took it off interface already
| before | after |
| ------ | ----- |
| <img width="200" alt="Screen Shot 2022-07-22 at 11 13 06 AM" src="https://user-images.githubusercontent.com/27475332/180469769-cf29b8be-456c-4bfc-a99a-486a7b59091a.png"> | <img width="200" alt="Screen Shot 2022-07-22 at 11 11 53 AM" src="https://user-images.githubusercontent.com/27475332/180469558-3bc6a8cf-9e91-41ae-869d-c87e5ab48f40.png"> |

feat: remove tooltip hops description

---

.github/workflows/release.yaml

This should allow us to test which version will be published before actually publishing.
Specifically, we can use it to ensure that the next version will be a major version release.

build: enable dry-run in release workflow

---

src/components/Swap/Summary/Summary.tsx

build was failing bc forgot to pass mandatory `open` prop to TransactionStatusDialog's usage of Summary component.
* Made `open` prop optional & default true

fix: set summary expando-open bool default true

---

src/components/ConnectWallet/ConnectWalletDialog.tsx

Pass in `container` theme color to button so that hover states use "container" theme
before:
after:

fix: use container color for button

---

src/components/Dialog.tsx
src/cosmos/Swap.fixture.tsx

Both left arrow & header text are now clickable in a dialog popup (as per design request)

fix: make header text clickable

---

src/components/ConnectWallet/ConnectWallet.tsx
src/components/Swap/SwapButton/index.tsx
src/components/Swap/index.tsx
src/components/TokenSelect/index.tsx
src/cosmos/Swap.fixture.tsx
src/hooks/connectWeb3/useWeb3React.tsx
src/hooks/useSyncEventHandlers.ts

- Prevents re-keying web3-react when `Widget` props change
Effectively, this was preventing state from updating in async handlers (such as event handlers).
- Simplifies event handler code throughout:
- Integrates typings in SwapProps
- Excludes values from hook deps (to reduce hook calls)
- Simplifies cosmos `useEventHandler` to handle all arguments

fix: respond to events

---

src/components/Swap/index.tsx
src/cosmos/ControlledSwap.fixture.tsx
src/cosmos/EventFeed.tsx
src/cosmos/Swap.fixture.tsx
src/hooks/swap/index.test.tsx
src/hooks/swap/index.ts
src/hooks/swap/useSyncController.ts
src/state/swap.ts
src/test/index.tsx

- This lets us "control" the widget without putting special-cased code throughout the components' logic

feat: allow controlling the widget

---

src/cosmos/Swap.fixture.tsx

Allows the cosmos fixture to be used (iframed) in the official documentation at https://docs.uniswap.org/sdk/widgets/swap-widget.

docs: iframe as simple widget

---

src/hooks/useERC20Permit.ts

Allows a user to trade _less than_ the signed amount in a swap.
Eg if a user allows 0.1 UNI to be swapped, this will allow 0.05 UNI to be swapped without requiring a new signature for the lesser amount.

fix: allow less than signed amount for swaps

---

src/components/ActionButton.tsx

Fixes a bug where the action overlay button (eg "Allow" when allowing a new currency) added 1em vertical padding, thus expanding the borders of the widget.

fix: action overlay height

---

src/components/Swap/SwapButton/index.tsx
src/components/Swap/SwapButton/useApprovalData.tsx
src/hooks/transactions/index.tsx

Zeroes out the inputs and sets Field.INPUT as the independent field (ie TradeType.EXACT_INPUT) once a swap or wrap is submitted. This is in line with github.com/Uniswap/interface, as per @infredible.
https://user-images.githubusercontent.com/5403956/186292639-13744922-1b1e-4fb4-b5ee-d5b477fd88c5.mov

feat: reset inputs after submission

---

src/components/Dialog.tsx
src/components/Swap/SwapButton/index.tsx
src/components/Swap/index.tsx
src/components/Widget.tsx
src/utils/animations.ts

This PR changes the transition behavior for modals.
If there is another dialog taking the place of an active one, the old dialog will slide out to the left (instead of to the right). In code, this is called "PAGING". This avoids risking exposing the screen underneath modals when they are replacing each other, and makes the modals look more sequenced.
It also fixes some issues I discovered while implementing this:
- Displays unwrap transactions, which was broken by #159 
- Delays input reset until after animations, to avoid layout thrashing
Before
https://user-images.githubusercontent.com/5403956/186477938-81c2ded0-4364-4bf9-a25d-4bf8a823710f.mov
After
https://user-images.githubusercontent.com/5403956/186519113-772405ce-da6e-44b4-9f8e-e551904cb471.mov

fix: slide modal out on other side

---

src/components/TokenSelect/TokenOptions.tsx
src/components/TokenSelect/index.tsx

Selects the top token from the token selector by default.
This allows a user to eg type `UNI<ENTER>` to use the UNI token, instead of needing to use arrows/mouse to select it from the list.

fix: token select with less friction

---

src/hooks/useSyncWidgetEventHandlers.ts

Fixes a bug where passing `onConnectWalletClick` to the atom updater caused infinite recursion, because passing a function runs that function and sets the return value. Instead, we want to set the function, so it should be returned from an anonymous function.

fix: set on connect wallet click

---

src/components/Swap/RoutingDiagram/utils.ts
src/components/Swap/Summary/Details.tsx
src/components/Swap/Summary/index.tsx
src/hooks/routing/clientSideSmartOrderRouter.ts
src/hooks/routing/transformSwapRouteToGetQuoteResult.ts
src/hooks/routing/useRouterArguments.ts
src/hooks/routing/useRouterTrade.ts
src/hooks/swap/index.test.tsx
src/hooks/swap/index.ts
src/hooks/swap/useSwapInfo.tsx
src/hooks/swap/useSyncController.ts
src/hooks/useSwapCallArguments.tsx
src/index.tsx
src/state/routing/slice.ts
src/state/swap/index.ts
src/utils/tradeType.ts

- Replaces usages of `independentField: Field` with `type: TradeType`, the primitive exposed through the SDK.
- Adds utilities (`invertTradeType` and `toTradeType`) to make it easier to deal with `TradeType`s.
- Replaces explicit checks of `tradeType === TradeType.EXACT_INPUT` with a boolean conversion `isExactInput` to standardize these checks.
- Standardizes `SwapController` to match internal `Swap` input (which makes internal conversion logic easier / unnecessary).

refactor: use TradeType instead of derived independent field

---

src/hooks/swap/useSyncTokenDefaults.ts
src/state/routing/slice.ts

```
$ tsc -p tsconfig.build.json && rollup --config --failAfterWarnings
src/hooks/swap/useSyncTokenDefaults.ts:64:7 - error TS2322: Type '{ amount: string; INPUT: Currency | undefined; OUTPUT: Currency | undefined; independentField: Field; }' is not assignable to type 'Swap'.
Object literal may only specify known properties, and 'independentField' does not exist in type 'Swap'.
64       independentField: Field.INPUT,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/hooks/swap/useSyncTokenDefaults.ts:69:24 - error TS2339: Property 'independentField' does not exist on type 'Swap'.
69       defaultSwapState.independentField = Field.OUTPUT
~~~~~~~~~~~~~~~~
src/state/routing/slice.ts:81:43 - error TS2345: Argument of type '{ type: string; tokenInAddress: string; tokenInChainId: ChainId; tokenInDecimals: …
```

chore: fix types related to tradeType

---

src/cosmos/ControlledSwap.fixture.tsx
src/cosmos/EventFeed.tsx
src/cosmos/Swap.fixture.tsx

Matches the event feed's height to the widget.
Uses a flex Row so that - if the DevTools are open to the right - the feed can go below the widget.
Fixes a testing pattern where opening DevTools would occlude the Widget being inspected.

test: responsive event feed

---

src/components/Swap/SwapActionButton/SwitchChainButton.tsx
src/constants/eip1193.ts
src/cosmos/ControlledSwap.fixture.tsx
src/cosmos/useProvider.ts
src/hooks/useSwitchChain.ts

Switches chains outside of web3-react. This makes it more portable (by not relying on the web3-react connectors), and avoids a bug where web3-react considers a connector inactive while it switches chains (thus temporarily changing to fallback connectors).

fix: switch chain outside of web3

---

src/components/ConnectWallet/ConnectWalletDialog.tsx
src/utils/WalletConnect.ts

use a more explicit activation pattern to avoid freezing the UI during activation
to test - try to connect a wallet. the current version freezes until the WC QR code has loaded.

fix: wallet connect activation

---

src/components/ActionButton.tsx

- Subtracts the padding value from the borderRadius, so the ActionButton's inset appropriately nests.

fix: action button border radius

---

src/polyfills.ts

**Problem:** Fixes #146 when NextJS does a server side render there is no `window` object so the server throws an error and crashes in the `polyfill.js` file. 
**Solution:** Since server side node shouldn't need the polyfill, just check if the window object exists. If it doesn't, we're server side and don't need to attempt to polyfill. 
NOTE: NextJS has explicit dead-code elimination for when guarding against an undefined window as `typeof window`, so this is the canonical way to check for SSR (see https://nextjs.org/blog/next-9#dead-code-elimination-for-typeof-window-branches).

fix: guard against undefined window for SSR (eg nextjs)

---

src/hooks/routing/useRouterTrade.ts
src/state/routing/slice.ts

Fixes triggering logic around the RTK query to refetch stale data, _without_ waiting an additional polling interval.

fix: refetch stale data

---

src/hooks/useSwitchChain.ts

In the current state of Web3React, activating another chain will temporarily disable the connector, which may lead to a different connector appearing active. For this reason, switching through EIPs 3085/3326 is always attempted first, with a fallback to activating another chain.

fix: attempt activate after switch

---

src/components/Swap/Input.tsx

Reverts Uniswap/widgets#236 due to a visual regression - it adds height to the initial screen without extending the widget or modals' heights

revert: "fix: add background color for swap Input"

---

src/hooks/useTokenList/index.tsx
src/index.tsx

Allow an empty token list to prevent any token list fetching.
Exports `UNISWAP_TOKEN_LIST` and `EMPTY_TOKEN_LIST`.

fix: allow empty token list

---

src/components/Swap/Input.tsx
src/components/Swap/TokenInput.tsx
src/components/TokenSelect/TokenButton.tsx
src/components/TokenSelect/index.test.tsx
src/components/TokenSelect/index.tsx

Moves max UI from the token button to the balance row.
Updating UX (ie setting focus after updating amount) will be done in a follow-up PR.
WEB-790

feat: move max ui

---

src/components/Error/ErrorDialog.tsx
src/components/Expando.tsx

https://uniswaplabs.atlassian.net/browse/WEB-1301?atlOrigin=eyJpIjoiOGFmOWQ0MTdlZjdjNGMxNDliNGQwMjg5N2EyOGFkNjkiLCJwIjoiaiJ9
the colors look off because our theme file is off from figma. i'll update all the colors in a separate pr.

fix: [Widget] change the "reload" button

---

src/components/Swap/Input.tsx
src/components/Swap/Output.tsx
src/components/Swap/index.tsx

This is a simplification from a previous ticket.
Consistently color balances, instead of making them darker when the widget is in focus.

fix: consistently color balance

---

src/components/Swap/Input.tsx
src/components/Swap/Output.tsx
src/components/Swap/ReverseButton.tsx
src/components/Swap/Skeleton.tsx
src/components/Swap/SwapActionButton/index.tsx
src/components/Swap/Toolbar/index.tsx
src/components/Swap/index.tsx
src/hooks/swap/index.ts
src/hooks/swap/useSwapInfo.tsx

- Propagates ChainError's through SwapInfo, so that checking for chain errors (which is error-prone) is not duplicated throughout the Widget.
- Refactors Toolbar and SwapActionButton to use ChainError to display errors:
- Resolves WEB-1446: when "Switch network" is visible, disable all other widget click targets
- Resolves WEB-1445: Clear toolbar when "Switch network" CTA is in Action Button

feat: chain errors

---

src/theme/type.tsx

Reduces the Caption font size to prevent overflow from occuring for some captions. See WEB-1514 for details.

revert: keep Caption font size at 12

---

src/components/TokenImg.tsx
src/hooks/useCurrencyLogoURIs.ts

Checks for logoURI so that non-standard Currencies passed in by an integrator may still have a logo displayed.

fix: check for logoURI on currency

---

src/components/Swap/Toolbar/Caption.tsx
src/components/Swap/Toolbar/index.tsx
src/components/TokenSelect/TokenButton.tsx

fix: center button and toolbar text with relevant icons

---

src/components/TokenImg.tsx
src/hooks/useCurrencyLogoURIs.ts

Fixes detection of logoURI, so that if a token is passed to the widget from an integrator with logoURI, it will correctly have its logo displayed.

fix: respect Currency.logoURI

---

src/components/TokenSelect/TokenButton.tsx

- Fixes the alignment of the token button, so that text is centered
- Fixes the widget of the alignment button, so that the chevron does not break onto the next line
Before:
After:

fix: token button row alignment and width

---

src/hooks/routing/useRouterTrade.ts
src/hooks/swap/useSwapInfo.tsx
src/hooks/usePriceImpact.ts
src/state/routing/args.ts

- Adds a RouterPreference.SKIP, to avoid querying the router for wraps and mismatched chains
- Updates the variable names in useComputeSwapInfo to be more self-documenting
- Includes USDC values for wraps (for parity with interface)
- Improves responsiveness by fetching USDC values for parsed amounts, instead of waiting for a trade to load
- Omits invalid slippage/impact by only fetching them once a valid trade has loaded, instead of doing so on stale trades while syncing
---
NB: This is easiest reviewed commit-by-commit due to variable renaming which otherwise clutters the diff.

fix: improve responsiveness of useSwapInfo

---

src/components/Swap/index.tsx
src/components/Widget.tsx
src/hooks/swap/useSyncController.ts
src/hooks/useInitialAtomValues.ts
src/hooks/useSyncBrandingSetting.ts

Avoids rendering branding or initial state for controlled widgets.

fix: initialize atoms with ui config for initial render

---

src/components/Swap/Input.tsx
src/theme/type.tsx

- Adds space between usd and impact using a gap, as it was not being respected as html
- Makes impact non-selectable (to further distinguish it from price)

fix: add space between usd, impact

---

src/components/Button.tsx
src/components/TokenSelect/TokenButton.tsx

Removes transitions between disabled token selector and enabled selection.
This is rarely used, and impedes the clean look of a widget initialized to a specific token.
WEB-1821

fix: omit token select transition

---

src/cosmos/Swap.fixture.tsx
src/hooks/routing/clientSideSmartOrderRouter.ts
src/hooks/routing/useRouterTrade.ts
src/hooks/swap/useSwapInfo.tsx
src/hooks/useUSDCPrice.ts
src/state/routing/args.ts
src/state/routing/slice.ts
src/state/routing/types.ts

Prices (and routes, if no routerUrl is specified) are loaded using the client-side router, which must initialize a route before it can fetch prices for it. Currently, this initialization is only done _after_ a swap is fetched (ie a waterfall pattern).
Updates the routing code to initialize a route as soon as its Token is selected. This has two important consequences: client-fetched swaps are significantly faster, since the delay is mostly initialization; prices show up (nearly) at the same time as the swap, since (again) the delay is mostly initialization.
Compare these two experiences for loading the DAI price (note the latter is instant):
https://user-images.githubusercontent.com/5403956/200449717-15747b84-2d1f-4c1c-b547-81388f968ff1.mov
_Before_ …

feat: preload client side routes

---

src/cosmos/ControlledSwap.fixture.tsx
src/hooks/swap/useSyncController.ts

Fixes a reset of the `<input>` state by ensuring the update can be processed synchronously.
Previously, controlled state had a delay because of the use of `useEffect` to detect changes. This was unnecessary, as the setter should be a nop if an update referentially equivalent to the current state is passed to it.

fix: retain cursor when updating controlled amount

---

src/components/Swap/ReverseButton.tsx

Adds an opaque underlayer to the ReverseButton to prevent leaking the underlying elements through when it is transparent.
This can be tested by viewing the widget with a wallet connection on the wrong chain. It is only visibly different when the ReverseButton is disabled.
_Before_
_After_

fix: use an opaque underlayer for reverse button

---

src/utils/swapErrorToUserReadableMessage.tsx

Prepares the way for universal-router, which will be throwing these strings as Error messages.

refactor: return swap errors as string

---

src/hooks/swap/useSwapApproval.ts
src/hooks/swap/useSwapInfo.tsx

Prepares the way for permit2, which will need to check approval for the same amount through a novel codepath.

refactor: pass approval amount from info

---

src/hooks/usePermit2.ts

Leaving info un-awaited caused unhandled rejections if the user did not accept the tx.
This correctly catches rejections.

fix: better sequencing to handle rejections

---

src/state/routing/utils.ts

Uses a stable value for the trade's currencies, so that hooks depending on the currency are not rerendered. Practically, this fixes an issue where changing the input amount would reset approval state.

fix: stable trade currency

---

src/components/Swap/SwapActionButton/SwapButton.tsx
src/hooks/swap/useSwapInfo.tsx
src/hooks/usePermit2.ts

Adds a PermitState.LOADING to avoid initiating a swap before PermitState is known.
This prevents swaps from failing because they have not yet been permitted.

fix: disable swap while permit loading

---

src/hooks/routing/clientSideSmartOrderRouter.ts
src/hooks/swap/index.ts
src/state/routing/slice.ts
src/state/routing/types.ts

- Correctly parse `0(.0*)+` as unpopulated amounts. This fixes a bug where entering `0` displayed the error caption.
- Disambiguate initialization in the client-side router. This fixes a bug where the toolbar displayed the insufficient liquidity caption on first load.

fix: error captions

---

src/components/Swap/SwapActionButton/SwitchChainButton.tsx
src/components/Swap/SwapActionButton/WrapButton.tsx

Prevents a user from double-sending transactions to their wallet (or the UX from implying that this is desirable given our UX flow).

fix: disable ActionButton whilst awaiting wallet action

---

package.json
yarn.lock

universal-router-sdk had used `instanceof` checks, which were failing for unknown reasons.
See https://github.com/Uniswap/universal-router-sdk/pull/94.

build: upgrade universal-router-sdk to fix instanceof checks

---

src/hooks/usePermitAllowance.ts

Fixes a bug where a user could submit a transaction, but would be required to re-sign a permit for a subsequent transaction, because the prior transaction's modification of allowance was not detected.

fix: observe submitted allowance immediately

---

src/components/Swap/SwapActionButton/SwapButton.tsx

If there is insufficient balance (or other swap-disabling error), do not show the approve button, but instead show a disabled swap button.
This fixes a regression in permit2, to align it with the legacy behavior.

fix: show error when present (not approval)

---

src/components/Swap/SwapActionButton/Permit2Button.tsx
src/components/Swap/SwapActionButton/SwapButton.tsx
src/hooks/useApproval.ts
src/hooks/usePermit2.ts
src/hooks/useTokenAllowance.ts

Add a `pending` state to `permit` which, once an approval is submitted, will flip to `true` and not flip back to `false` until the allowance has re-synced. This ensures that the UI stays in a pending state until an approval is processed, without re-prompting for approval.

fix: await syncing allowance to update permit state

---

src/components/Swap/SwapActionButton/AllowanceButton.tsx
src/components/Swap/SwapActionButton/SwapButton.tsx
src/hooks/usePermit2Allowance.ts

Moves approval tracking into its callback, so that a rejection of signing does not discard tracking the approval.

fix: track approval even if signature is rejected

---

src/assets/svg/reverse.svg
src/components/Swap/ReverseButton.tsx
src/icons/index.tsx

updates the "reverse input/output currencies" icon to match design
design file: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10381%3A101862&t=VFd894XSQCCzBYD0-4
verified that this correctly flips colors between light and dark mode

feat: change reverse icon

---

src/components/Widget.tsx
src/i18n.tsx

simply moving the i18n initialization logic to the `I18nProvider` since it doesn't need to exist in the top level `Widget`. Tested and verified that the behavior is unchanged.

feat: move i18n initialization logic to the Context Provider

---

src/components/Error/ErrorBoundary.tsx
src/errors.ts

Simplifies async error throwing using the method detailed in https://medium.com/trabe/catching-asynchronous-errors-in-react-using-error-boundaries-5e8a5fd7b971.
Follow-ups:

fix: simplify async error throwing

---

src/components/ActionButton.tsx
src/components/Input.tsx
src/components/Swap/Input.tsx
src/components/Swap/Output.tsx
src/components/Swap/ReverseButton.tsx
src/components/Swap/TokenInput.tsx
src/components/Swap/Toolbar/index.tsx
src/components/TokenSelect/TokenButton.tsx
src/components/WidgetWrapper.tsx
src/theme/index.tsx
src/theme/theme.ts
src/theme/type.tsx

design spec: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10575%3A115233&t=VFd894XSQCCzBYD0-4
updates sizings, spacings, and colors for the main widget root component, and the input/output fields. This PR focuses on the "input" step, which includes the initial view with and without tokens selected.
this also updates the colors in the theme to match the new design.

feat: styling updates to widget input step

---

src/components/Dialog.tsx
src/components/Header.tsx
src/components/Popover.tsx
src/components/Swap/Settings/index.tsx
src/components/Swap/index.tsx
src/hooks/useCloseOnEscape.tsx
src/hooks/useOnEscapeHandler.tsx

This PR converts the settings menu from a slide-in dialogue to a popover menu
https://user-images.githubusercontent.com/59578595/211571182-0b35482d-f415-4fe0-8e22-46b9b68efee5.mov
Some other notes:
- removed a `Header button` css property that was effecting sizing of all child buttons - we should define these at an individual level
- followup to do mobile-friendly modal view 
- followup to add drop shadows
Questions:
- should we add a min-width for the menu?

feat: Convert settings into popover

---

e2e/connect.test.tsx
e2e/test/index.ts
src/hooks/swap/useSyncController.ts

- Uses a pure act-free environment for testing, so that state changes not wrapped in `act` are permissible
- Avoids settings controlled state when not used, to avoid the "called setState during render" warning

test: eliminate warnings in e2e testing

---

src/components/Popover.tsx
src/components/Tooltip.tsx

- Adjusts offset so that the tooltip chevron is centered
- Uses state instead of a ref so that tooltips are shown immediately

fix: tooltip fixes

---

src/components/Swap/SwapActionButton/SwapButton.tsx
src/components/Swap/SwapActionButton/index.tsx

Removes approval logic from the SwapButton, now that buttons are separated/decoupled in the UI.

fix: simplify swap disabled state

---

src/constants/jsonRpcEndpoints.ts
src/hooks/routing/useRouterTrade.ts
src/hooks/useTimeout.ts

- Omits rate-limited polygon RPC endpoints
- Fixes useTimeout to only trigger a callback once, after the timeout
- Fixes useRouterTrade to avoid infinite retries when erring

fix: improve routing experience

---

src/components/Swap/Settings/index.tsx

[slack](https://uniswapteam.slack.com/archives/C04JP2P3F7T/p1673506938838779?thread_ts=1673506038.511189&cid=C04JP2P3F7T) convo for context

fix: Remove spin state on un-hovering settings icon

---

jest.config.js
package.json
src/components/Swap/Input.tsx
src/components/Swap/Toolbar/Caption.tsx
src/components/Swap/Toolbar/index.tsx
src/theme/index.tsx
test/setup-jest.ts
yarn.lock

- use a new Caption type for price impacts
- update colors for price impact messages
- fix bug with displaying price impact below the output field

feat: toolbar updates for price impacts

---

src/constants/chainInfo.ts
src/hooks/useSwitchChain.ts

Fixes the MetaMask `wallet_addEthereumChain` integration:
- Does not call `wallet_switchEthereumChain` after `wallet_addEthereumChain`, as MM automatically prompts to switch to a newly added wallet
- Stops attempting to add a chain after a successful call to `wallet_switchEthereumChain`. This fixes an issue where chains were added multiple times with different RPC providers.
- Fixes warnings displayed by MM when adding chains by conforming to MM's expected chain metadata using `safe` parameters for chain info.

fix: chain switch once and without warnings

---

src/components/Swap/Input.tsx
src/components/TokenSelect/TokenButton.tsx

- move TokenImg out from under the `ThemedText`, because the larger font it inherits was breaking the `em` spacing

fix: spacing bug with em in TokenButton

---

src/components/ActionButton.tsx
src/components/Input.tsx
src/components/Swap/Input.tsx
src/components/Swap/Settings/TransactionTtlInput.tsx
src/components/Swap/Settings/components.tsx

- add missing border to settings input
- use 'primary' text color for disable buttons
- fix casing for input sub header
https://www.notion.so/uniswaplabs/widget-design-feedbacks-835bfad85aac4ad3a00550fcea18bf99
design spec: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10305%3A105762&t=GMFoRG5hj2E6QPEd-0

fix: polish design issues in widget

---

src/components/ActionButton.tsx
src/components/Error/ErrorDialog.tsx
src/theme/index.tsx
src/theme/theme.ts

update colors for the error dialog
note: the "code" font is subject to this [issue](https://github.com/Uniswap/interface/issues/3343)
design spec: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10575%3A122757&t=GMFoRG5hj2E6QPEd-4

feat: update colors in error dialog

---

src/components/EtherscanLink.tsx
src/components/Swap/Status/StatusDialog.tsx
src/theme/type.tsx

design for this screen: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10369%3A106419&t=ijfa7EEMSPInWNSl-4
updates the fonts and placement of the UI elements on the "waiting for confirmation" and "success" screens

feat: update ui for tx status dialog

---

src/components/BottomSheetModal.tsx
src/components/Expando.tsx
src/components/Swap/Settings/MaxSlippageSelect.tsx
src/components/Swap/Settings/TransactionTtlInput.tsx
src/components/Swap/Settings/index.tsx
src/components/Swap/Toolbar/Caption.tsx
src/components/Swap/Toolbar/index.tsx
src/hooks/useScrollbar.ts
src/icons/index.tsx

This PR moves the inner content of the settings menu into `Expando` components
https://user-images.githubusercontent.com/59578595/213023578-d96515e8-4be6-45d3-b3e6-224a59794413.mov
https://user-images.githubusercontent.com/59578595/213023731-b2ea3384-faed-4af1-9368-b2b2c0596bef.mov
Followups:
- add the "routing api" settings option
- looks like the "max slippage" option has different sub designs too, will change in a followup PR

feat: Move settings menu into expandable components

---

src/assets/svg/large_arrow.svg
src/components/ActionButton.tsx
src/components/Error/ErrorDialog.tsx
src/components/Swap/Status/StatusDialog.tsx
src/components/Swap/Summary/index.tsx
src/components/Swap/SwapActionButton/WrapButton.tsx
src/components/Widget.tsx
src/constants/misc.ts
src/icons/index.tsx

we want to show this state for one second before the spinner state
https://user-images.githubusercontent.com/66155195/213035780-e126bde3-f9ba-483c-b47f-095178706dd5.mov

feat: add confirmation step to the StatusDialog flow

---

src/components/Swap/RoutingDiagram/index.tsx
src/components/Swap/Toolbar/ToolbarOrderRouting.tsx
src/components/Swap/Toolbar/__snapshots__/ToolbarOrderRouting.test.tsx.snap

[see updated design](https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=11388%3A110999&t=DBqcwSK7XYGI0Y55-4)
we want the RoutingDiagram to appear in a tooltip over the "Auto Router" label on the right, not as an Icon on the left.

feat: move RoutingDiagram tooltip

---

src/components/Swap/Toolbar/index.tsx

fixes a bug where we show an empty toolbar in the `ChainError.MISMATCHED_CHAINS` case
we can just default to showing the ActionButton here, since it already has the error message and a button to switch.
(draft until design confirms this behavior)

fix: remove toolbar when on mismatched chain

---

src/components/Dialog.tsx
src/components/Swap/RoutingDiagram/index.tsx
src/components/Swap/Toolbar/Caption.tsx
src/components/Swap/Toolbar/ToolbarOrderRouting.tsx

based on the [design spec](https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=1708%3A26043&t=5QXnxfgYI7whcjzT-0)
the routing diagram tooltip should also become a bottom sheet on smaller screens. this PR updates the two callsites for of RoutingDiagram to optionally wrap it in the BottomSheetModal.
also, fixes a width issue with the bottom sheet dialog

feat: use bottom sheet for routing diagram

---

src/components/Swap/Input.tsx

use conedison to format the numbers in the Input step. condeson follows our number formatting guidelines.

fix: use conedison to format numbers in Inputs

---

src/components/Swap/Input.tsx

based on design feedback, we want to lose focus on the input when clicking max. this is also how the swap component works in interface currently.

fix: lose focus on input when clicking max

---

src/theme/index.tsx

see the input placeholder color here: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10298%3A104518&t=MPVEUGMwd2mLGl3t-4

fix: hint color in dark theme

---

src/components/Swap/Toolbar/Caption.tsx
src/components/Swap/Toolbar/ToolbarOrderRouting.tsx
src/components/Swap/Toolbar/ToolbarTradeSummary.tsx

fixes a bug where the tooltips appear in totally wrong locations after the toolbar is expanded. using "auto" placement fixes the issue for all toolbar tooltips

fix: use auto placement on toolbar tooltips

---

src/components/Swap/Toolbar/index.tsx

prefer the "insufficient balance" caption instead of approval button.
this helps the user avoid an extra approval transaction before trying to complete a trade that they don't have the balance for.

fix: prefer insufficient balance caption over approval flow

---

src/components/Swap/Toolbar/Caption.tsx
src/components/Swap/Toolbar/GasEstimateTooltip.tsx

- moved the GasEstimate tooltip into it's own file, because it's a bit large
- reworked the rendering logic for GasEstimate to be more clear - and so the tooltip will appear when hovering over the text as well as the icon

fix: show gas estimate tooltip over text and icon

---

src/components/Swap/Summary/index.tsx

from design from the testing session: "we should put a cancel button here. just ran into an issue where WC or rainbow bugged out, and I had no way to confirm the txn in wallet. meanwhile this state is persisting"
design spec link: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=11464%3A109782&t=y8WEesOQvG6h2Oop-4
so with this button, we'll always allow the user to cancel and revert the UI to the non-pending state.

fix: show cancel button on review step

---

src/components/Error/ErrorBoundary.tsx
src/components/Error/ErrorDialog.tsx
src/components/Swap/Status/StatusDialog.tsx

Update swap failed modal to exclude the actual error object, as one is not provided by ethers.
If we want to capture an error object, it will need to be done separately, in SwapButton.tsx.
WEB-2793

fix: swap failed modal

---

package.json
yarn.lock

Upgrades @uniswap/universal-router-sdk to fix a bug where legacy wallets submitted unhandled legacy signature formats, with suffixes that failed to execute when calling estimateGas.
See ticket CX-140

fix: sanitize legacy signature format

---

src/components/BottomSheetModal.tsx
src/theme/index.tsx
src/theme/theme.ts

gives bottom sheet modals a higher zIndex by default - this is also configurable by the integration theme, so anyone can specify where exactly the modals should appear on the z Index
I tested this by installing a build in `interface` and verifying that I could make the bottom sheet appear over the Mobile Nav Bar

feat: add modal zIndex to theme definition

---

src/hooks/transactions/index.tsx
src/widgets.d.ts

include the Transaction Info in the `OnTxSuccess` callback - this gives the integrator access to the trade info easily without caching it themselves.
`BREAKING CHANGE`

feat: include tx info in OnTxSuccess

---

src/components/Swap/Price.tsx

according to our [Number Formatting standards](https://www.notion.so/uniswaplabs/Number-standards-fbb9f533f10e4e22820722c2f66d23c0), it's actually more appropriate to use this formatter here since it's not the input or output field. this fixes the layout issue on smaller widths

fix: use correct conedison formatter for trade quote

---

src/components/Swap/Status/StatusDialog.test.tsx
src/components/Swap/Status/StatusDialog.tsx

[design request](https://www.notion.so/uniswaplabs/Widget-design-feedback-835bfad85aac4ad3a00550fcea18bf99): remove the "pending" step in this dialog. instead of showing the spinner, we'll transition directly from the "submitted" state to the "success" state (or error state)

feat: remove pending step

---

src/components/Expando.tsx

i'm not sure why inlining this JSX fixes this error :/
```
Error when using sourcemap for reporting an error: Can't resolve original location of error.
{
column: 12,
file: '/Users/eddie.dugan/Documents/widgets/src/components/Expando.tsx',
line: 12
} 
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
{
column: 12,
file: '/Users/eddie.dugan/Documents/widgets/src/components/Expando.tsx',
line: 12
} 
```

fix: rollup error in Expando

---

src/components/ActionButton.tsx
src/components/Row.tsx
src/components/Swap/Input.tsx
src/components/Swap/Output.tsx
src/components/Swap/PriceImpactRow.test.tsx
src/components/Swap/PriceImpactRow.tsx
src/components/Swap/Summary/Details.tsx
src/components/Swap/TokenInput.tsx
src/components/Swap/Toolbar/__snapshots__/ToolbarOrderRouting.test.tsx.snap
src/components/Swap/Toolbar/index.tsx
src/components/Tooltip.tsx

- reduce vertical spacing between elements in the widget
- reduce the height of the toolbar
- add price impact tooltips everywhere we show the value (only shown if warning is "error" or "warning")
- use a new component for this. added tests for new component
- add token icons to summary page

feat: small design updates

---

src/constants/chains.ts
src/hooks/routing/clientSideSmartOrderRouter.ts
src/hooks/routing/transformSwapRouteToGetQuoteResult.ts
src/hooks/routing/types.ts
src/hooks/routing/useRouterTrade.ts
src/state/index.tsx
src/state/routing/args.ts
src/state/routing/slice.ts
src/state/routing/types.ts
src/state/routing/utils.test.ts
src/state/routing/utils.ts
src/utils/currencyId.ts

Our logic previously was set up such that the transform from quote result -> Trade was happening outside of rtk-query. This resulted in a tricky edge case during refetching where input/outputs were unsynced. Steps to repro:
- Get a quote for 0.1 ETH -> DAI. rtk-query returns the quote response, and `data` and `currentData` get filled in.
- Revise quote to 0.1 USDC -> DAI. rtk-query refetches. `data` is the cached result from the previous response, with the route for `ETH -> DAI`. `currentData` is undefined during the refetch.
- We're now creating a `Trade` object using the USDC -> DAI inputs but using `data` that has an ETH -> DAI route. This would error, but we had a [line](https://github.com/Uniswap/widgets/blob/main/src/state/routing/utils.ts#L24) that caught this case:
```
if …
```

chore: Transform quote results into Trades within rtk-query

---

src/components/Dialog.tsx

fixes a bug where dialogs incorrectly overflowed the widget boundary

fix: clip dialogs at corners

---

src/hooks/useCurrencyLogoURIs.test.tsx
src/hooks/useCurrencyLogoURIs.ts

default to the github URL for the token image first, if there is one.
this fixes a [feedback](https://www.notion.so/uniswaplabs/Using-different-token-images-in-widget-as-interface-and-are-sometimes-lower-res-36ccabc4384645189772ec7f65facee3) we received about the token images differing from what's shown on interface /swap page

fix: prefer the github-hosted token img

---

package.json
yarn.lock

Upgrades conedison to improve signing.
conedison@1.3 updates signTypedData to default to eth_signTypedData_v4 and only use eth_signTypedData for special-cased wallets.
---
Manually tested on:

feat: upgrade conedison to improve signing

---

src/components/WidgetWrapper.tsx

reduces the widget min height to fix a layout issue when both `hideConnectionUi` is true and `brandedFooter` is false

fix: reduce widget min height

---

src/components/Swap/SwapActionButton/SwapButton.tsx
src/components/Swap/SwapActionButton/useOnSubmit.ts
src/components/__snapshots__/Header.test.tsx.snap
src/hooks/useUniversalRouter.ts
src/utils/swapErrorToUserReadableMessage.tsx

stop throwing `SwapError`s when the user rejects the Transaction. instead, if we detect that the user rejected, just notify the product code via the return value. for now, we swallow the error and just revert the UI so they can try again. but we may want to show a message inline in this situation
https://uniswaplabs.atlassian.net/browse/WEB-2888?atlOrigin=eyJpIjoiYTg1YWFiZDYwMGM2NDc3NWJmOGRiZGE3NGNmNGQyZTQiLCJwIjoiaiJ9

fix: swallow transaction rejected error

---

package.json
yarn.lock

Resolves an issue with permit signatures not working with smart contract wallets.

chore: upgrade universal-router-sdk

---

src/components/Swap/Summary/index.test.tsx
src/components/Swap/Summary/index.tsx
src/constants/misc.ts
src/utils/tradeMeaningFullyDiffer.ts

Simplifies review state by combining reviewing & trade impact views into one. Adds a threshold for when to show a price change warning

feat: threshold and state simplification

---

src/components/Dialog.tsx
src/cosmos/Swap.fixture.tsx

adds a new option to `DialogAnimationType` to allow for *no* animation.
this would allow integrators to animation the dialog however they want, at the container level

feat: dialog no animation

---

src/components/Dialog.tsx

changes the dialog "close" button to an `X` icon , if it's _not_ sliding in from the right

feat: x button for dialogs

---

src/components/Swap/Summary/Details.tsx
src/components/Swap/Toolbar/index.tsx

addresses some [design feedback](https://www.notion.so/uniswaplabs/Widget-design-feedback-835bfad85aac4ad3a00550fcea18bf99) about the formatting and styling of the price impact.
- remove parens from the % in the review screen
- use `toString` everywhere to ensure consistent values

fix: make price impact more consistent

---

src/components/Swap/Toolbar/Caption.tsx
src/components/Swap/Toolbar/index.tsx

adds a different loading state to the `Trade` caption in the toolbar. instead of replacing all the text with "Fetching Trade", we:
- add a loading spinner next to the exchange rate
- make the exchange rate 0.4 opacity

feat: loading state for toolbar Trade

---

src/components/BottomSheetModal.tsx
src/components/Dialog.tsx
src/components/Swap/Settings/MaxSlippageSelect.tsx
src/components/Swap/Settings/TransactionTtlInput.tsx
src/components/Swap/Settings/components.tsx
src/components/__snapshots__/Header.test.tsx.snap
src/hooks/useIsMobileWidth.ts
src/icons/index.tsx

see the design feedbacks [here](https://www.notion.so/uniswaplabs/Settings-responsiveness-issues-and-design-refinement-606be8f282cb403dae1147b79ce16b06?pvs=4)
list of changes:
- change arrow icon to x icon
- introduce max-width to elements in these expando rows
- adjust input visuals slightly
- change icons for tooltips
- change mobile breakpoint

fix: design issues in settings

---

src/components/Dialog.tsx
src/components/Error/ErrorBoundary.tsx
src/components/Swap/Summary/index.tsx
src/components/TokenSelect/TokenOptions.tsx
src/cosmos/Swap.fixture.tsx

adds an option to the Widget API which enables page-centered dialogs without any configuration. 
if they are enabled, we mount our dialogs at the page root and make them full screen. if Dialogs are page-centered, then their content needs to define their own size rather than assume the parent's size will be defined. (see my adjustments to the `SummaryDialog` and `TokenOptions` for examples).
note: i'm currently forcing errors to stay centered in the widget because it's a better UX imo.

feat: widget page-centered dialogs

---

src/components/Swap/Toolbar/index.tsx

We are currently catching the no routes state as "missing input" instead of displaying a trade error

fix: Handle no routes state in toolbar

---

src/components/Button.tsx
src/components/__snapshots__/Header.test.tsx.snap

we should also update the color of nested texts in the `TextButton` component
note, in this screenshot i'm hovering over the quote but the mouse isn't captured

fix: change usd text color on hover

---

src/components/Swap/Toolbar/index.tsx

[feedback link](https://www.notion.so/uniswaplabs/Auto-router-tooltip-looks-off-small-relative-to-rest-of-the-font-and-UI-dfc67677064d4e2c9fddc9babca07083?pvs=4)
passes the Gas Estimate to the Routing Tooltip in this case too, because apparently they should match

fix: use larger RoutingDiagram in Toolbar

---

src/errors.ts

[see design here](https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=1708%3A26043&t=b0V5aEN9cKtpFUZH-0)
"Sorry, an error occured while processing your request. Please try again or contact support." is now the default message in error dialogs

feat: update swap error default message

---

src/components/BottomSheetModal.tsx
src/components/Dialog.tsx
src/components/Popover.tsx
src/components/Swap/Settings/MaxSlippageSelect.tsx
src/components/Swap/Settings/RouterPreferenceToggle.tsx
src/components/Swap/Settings/components.tsx
src/components/Swap/Settings/index.tsx
src/components/Swap/Toolbar/__snapshots__/ToolbarOrderRouting.test.tsx.snap
src/components/__snapshots__/Header.test.tsx.snap

fixes the "auto-dismiss" bug (see `Dialog` change)  [link](https://www.notion.so/uniswaplabs/On-mobile-web-trying-to-edit-slippage-dismisses-the-bottom-sheet-modal-instead-33cd786e636d46f8a8d14a33ebe80421?pvs=4)
fixes icon aligments (see `Popover` change and changes in settings components) [link](https://www.notion.so/uniswaplabs/All-icons-in-settings-appear-a-little-misaligned-1b588c96be3245bea141f4974ef7554b?pvs=4)
fixes Auto slippage issue [link](https://www.notion.so/uniswaplabs/Setting-a-custom-slippage-number-then-switching-back-to-Auto-doesn-t-reset-the-slippage-number-in-3af1668dd3494ebf9eadbf8879817798?pvs=4)

fix: settings icon alignment and bugs

---

src/components/Popover.tsx
src/components/Swap/Settings/MaxSlippageSelect.tsx
src/components/Swap/Settings/RouterPreferenceToggle.tsx
src/components/Swap/Settings/TransactionTtlInput.tsx

There are some more issues w/ this tooltip/popper setup that I'd like to fix eventually, but this change makes the tooltip usable with our `Expando` component at least

fix: don't propogate tooltip clicks to their parents

---

src/components/Popover.tsx
src/components/Swap/Summary/index.tsx
src/components/TokenSelect/TokenOptions.tsx
src/components/__snapshots__/Header.test.tsx.snap
src/hooks/useWindowWidth.ts

- remove the manual trigger from `Popover`, instead automatically update like we do in `interface` ([link](https://github.com/Uniswap/interface/blob/main/src/components/Popover/index.tsx#L117))
- change the min width of dialogs to not overflow small width screens

fix: tooltip and modal updates

---

src/components/Logo/index.tsx
src/components/TokenImg.tsx
src/components/TokenSelect/TokenButton.tsx

fixes the default token image - we need the token symbol to show the first 3 letters. also, the dot was too small because we were using `em` instead of `rem`

fix: default token images

---

src/components/BottomSheetModal.tsx
src/components/Dialog.tsx
src/components/Error/ErrorDialog.tsx
src/css/hover.ts
src/icons/index.tsx

see design here: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=12156%3A118039&t=b0V5aEN9cKtpFUZH-0
adds an "x" icon to close the error dialog

feat: add close button to error dialog

---

src/hooks/routing/useRouterTrade.ts

make sure we show a loading state while fetching the next quote, even if the most recent cached result is a "not route found" error !

fix: loading state post-error

---

src/components/Swap/SwapActionButton/index.tsx
src/hooks/useCurrencyBalance.ts

https://uniswaplabs.atlassian.net/browse/WEB-2766?atlOrigin=eyJpIjoiNTA4OGVmZWI5ZTJhNDMyMThhMjkwOGRkZjc0NjBhMmUiLCJwIjoiaiJ9
we want to stop blocking swap if the balances aren't loaded to match the current behavior in interface.
if the balance IS loaded, we should still disable the button if the user doesn't have enough funds

fix: stop blocking swap on balance fetching

---

src/components/TokenSelect/TokenOptions.tsx
src/components/TokenSelect/index.tsx

fixes a bug where the token list was being cut off in the non-page-centered version of the widget.

fix: contained tokenlist height

---

jest.config.js
package.json
src/constants/misc.ts
src/hooks/usePermitAllowance.ts
src/hooks/useUniversalRouter.ts
test/setup-jest.ts
yarn.lock

Uses `@uniswap/conedison/provider` implementation of `sendTransaction`, which includes a gas margin computation.
It also omits the gas margin computation for Uniswap Wallet, and uses sendUncheckedTransaction under the hood. This allows the app to be linked to within 300ms, which allows iOS to deep-link through WalletConnect to the mobile app instead of navigating the to app's webpage.
To test (this may not work on cloudflare/vercel deploys - I'm not sure why, but it may be because they add instrumentation):
- Using your iOS device, connect to the App using Uniswap Wallet via WalletConnect
- Initiate a swap/wrap/etc on the app
- The application should deep-link directly to the wallet
Requires https://github.com/Uniswap/conedison/pull/13 to poll before merging.

fix: deep link by swapping sooner after user interaction

---

src/components/Swap/Toolbar/Caption.tsx
src/components/Swap/Toolbar/ToolbarContext.tsx

for some reason, changing these `const`s to regular `function` syntax fixes the rollup errors that we've been seeing (in the terminal when running `yarn start`)
example of the error:
```
rollup building...
Error when using sourcemap for reporting an error: Can't resolve original location of error.
{
column: 13,
file: '/Users/eddie.dugan/Documents/widgets/src/components/Swap/Toolbar/Caption.tsx',
line: 4
} 
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
{
column: 13,
file: '/Users/eddie.dugan/Documents/widgets/src/components/Swap/Toolbar/Caption.tsx',
line: 4
} 
```
to verify that this actually fixes the errors like I claim, checkout this branch and run `yarn && yarn start`

fix: rollup errors

---

src/components/BottomSheetModal.tsx
src/components/Popover.tsx
src/components/ResponsiveDialog.test.tsx
src/components/ResponsiveDialog.tsx
src/components/Swap/Settings/index.tsx
src/components/Swap/SwapActionButton/SwapButton.tsx
src/components/TokenSelect/index.tsx
src/components/__snapshots__/Header.test.tsx.snap

this PR is just trying to reduce code duplication - we have similar logic in a few places for switching between Bottom Sheets and Popovers/Dialogs depending on the screen size. 
screen recordings:
widget-contained dialogs, slide animation:
https://user-images.githubusercontent.com/66155195/223275255-5d6ed05b-b9b1-4dc1-a0cc-375538c35856.mov
widget-contained dialogs, fade animation:
https://user-images.githubusercontent.com/66155195/223275470-446cc02a-8a54-4c4d-9125-d6bd9a18717d.mov
page-centered dialogs, fade animation:
https://user-images.githubusercontent.com/66155195/223276227-36a9074a-3810-4d24-9cbc-00e01c19ac9d.mov

feat: refactor dialogs and bottom sheets

---

src/components/Swap/Toolbar/ToolbarContext.tsx
src/components/Swap/Toolbar/index.tsx
src/components/Swap/index.tsx

collapse the toolbar when we switch to a wraping swap
https://user-images.githubusercontent.com/66155195/223544975-b35b4a95-263b-4a58-8569-24064dfd20c5.mov
https://user-images.githubusercontent.com/66155195/223544801-105fac31-89ef-4e7d-916d-32bfda5227c6.mov

fix: collapse toolbar for wrap transactions

---

src/hooks/routing/clientSideSmartOrderRouter.ts
src/hooks/routing/transformSwapRouteToGetQuoteResult.ts
src/hooks/routing/useRouterTrade.ts
src/state/routing/slice.ts
src/state/routing/types.ts
src/state/routing/utils.test.ts
src/state/routing/utils.ts

Narrows typings for router queries, which avoids having to coerce types in useRouterTrade.
This will enable cleaner code for a planned perf event hook (see #549).
Also uncovers and fixes a bug for swaps with no quote (`QuoteState.NOT_FOUND`), which do not include a `blockNumber` but should still be rendered.

fix: stricter typing for router query

---

src/components/Swap/Summary/Details.tsx
src/components/Swap/Summary/Estimate.tsx
src/components/Swap/Summary/index.tsx

fix some small design nits that I and others noticed in dogfooding:
- add more padding between output "i" icon and value
- increase vertical padding between summary header and body and button
- prevent the slippage text from wrapping so early

fix: summary dialog layout nits

---

src/components/Swap/Toolbar/index.tsx

it's redundant to show "error fetching trade" when we know the error - there's not enough liquidity to calculate a trade between these tokens. in this case we should just hide the toolbar.
https://www.notion.so/uniswaplabs/Generic-error-fetching-trade-when-the-error-state-is-insufficient-liquidity-and-displayed-in-the-9d04b1253f38425b89b3edfa0b5927ec?pvs=4

fix: hide toolbar when insufficient liquidity

---

src/components/Swap/Toolbar/ToolbarContext.tsx

collapse the toolbar when missing an input - this is not a common case and i can't reliably reproduce, but i did encounter the issue once so i feel that we should manually close in this case

fix: collapse toolbar when missing inputs

---

src/components/Dialog.tsx
src/components/Swap/Speedbump/index.tsx
src/components/Swap/Summary/index.tsx
src/components/Swap/Toolbar/ToolbarContext.tsx

adjust the max-width of the price impact speed bump content
https://www.notion.so/uniswaplabs/Weird-UI-state-of-warning-modal-746px-52f715bda79c466d89e5b08d374f10b5?pvs=4

fix: width of price impact speedbump

---

src/cosmos/EventFeed.tsx

Adds a filter to the cosmos event feed to aid debugging.

test: add filter to event feed

---

package.json
yarn.lock

upgrades the Smart Order Router dependency because we want this bug fix: https://github.com/Uniswap/smart-order-router/pull/211
this fixes an issue Opensea is having with their integration related to `provider` compatibility.
-----
also, remove the dynamic import for the client side routing code. this code splitting is not working for third party integrators using next.js.

feat: upgrade sor

---

src/components/Swap/PriceImpactRow.tsx
src/components/Swap/Settings/TransactionTtlInput.tsx
src/components/Swap/Toolbar/Caption.tsx
src/components/Swap/Toolbar/index.tsx
src/components/WidgetWrapper.tsx
src/components/__snapshots__/Header.test.tsx.snap
src/cosmos/SwapSkeleton.fixture.tsx
src/theme/index.tsx
src/theme/theme.ts

adds a warning UI to the expander on the right when the toolbar is collapsed  - IF there is a price impact warning to view in the expanded state.

feat: new warning UI in toolbar

---

src/components/Swap/SwapActionButton/SwapButton.tsx

the callback we pass to `onSubmit` requires the transaction info be returned if successful. this was removed in #553 , probably because it seemed unnecessary? cc @zzmp 
this re-adds the missing return statement with a comment indicating it's required
verified that the StatusDialog appears properly now when you submit a transaction

fix: replace missing return value from swap callback
