Uniswap/widgets

- src/components/TokenSelect/TokenButton.tsx
| before | after |
| ----- | -----  | 
| <img width="200" alt="Screen Shot 2022-07-22 at 11 46 43 AM" src="https://user-images.githubusercontent.com/27475332/180475967-3082360c-06b0-448c-bf74-79b6655f894b.png">  <img width="200" alt="Screen Shot 2022-07-22 at 11 46 47 AM" src="https://user-images.githubusercontent.com/27475332/180475984-f3af97ee-b2cd-4e83-8c04-d6f3fd3d3e8f.png">  |  <img width="200" alt="Screen Shot 2022-07-22 at 11 40 16 AM" src="https://user-images.githubusercontent.com/27475332/180475634-06f8c613-efd8-447d-8ed7-9359f8358ebb.png"> <img width="200" alt="Screen Shot 2022-07-22 at 11 40 10 AM" src="https://user-images.githubusercontent.com/27475332/180475719-2d6b36ea-5065-4972-afbb-380bc53feb2f.png"> |
> fix: disabled token button text color should use correct colors

- src/cosmos/Swap.fixture.tsx
> feat(cosmos): Add events to cosmos

- src/components/Button.tsx
- src/components/Dialog.tsx
- src/components/Header.tsx
Fixes alignment of the info icon.
Updates header and icon button heights to avoid misalignments.
See https://uniswaplabs.atlassian.net/browse/WEB-891.
> fix: icon button height

- src/components/Input.tsx
- src/components/Swap/Settings/MaxSlippageSelect.tsx
Increases the padding to 0.75em (from 0.5em).
> fix: text input padding

- src/components/Swap/SwapButton/index.tsx
Fixes a bug introduced in #159 which always disabled wrapping.
> fix: re-enable wrapping

- src/cosmos/ControlledSwap.fixture.tsx
ts errors here
- (can't have `undefined`) from the fixture controller
- must have `Field` keys
> fix: add correct values to example

- src/components/Swap/Input.tsx
- src/components/Swap/Output.tsx
Always shows the balance in the UI, if available.
> fix: persist balance in UI

- src/hooks/connectWeb3/useWeb3React.tsx
Rekeys the Web3ReactProvider in the same effect that updates connectors, to avoid Web3ReactProvider throwing when connectors change.
Fixes https://uniswaplabs.atlassian.net/browse/WEB-1000.
> fix: re-key web3react when connectors change

- src/constants/jsonRpcEndpoints.ts
Fallback to "Safe" URLs first, as defined by the MetaMask implementation.
> fix: fallback urls

- src/components/ConnectWallet/ConnectWalletDialog.tsx
- src/constants/jsonRpcEndpoints.ts
- src/hooks/web3/index.tsx
- src/hooks/web3/useConnectors.tsx
- src/utils/WalletConnect.ts
- Clarifies the two WalletConnect instances by creating subclasses
- Moves the svg generation logic out of React and into WalletConnectQR
> fix: clarify WalletConnect flows

- e2e/connect.test.tsx
- src/components/Swap/SwapActionButton/SwitchChainButton.tsx
Fixes an infinite loop when switching the defaultChainId
> fix: only switch chain once

- src/components/Swap/SwapActionButton/SwitchChainButton.tsx
- src/components/Swap/Toolbar/index.tsx
- Prompts for network switch even if there is no account
- Removes the toolbar CTA when prompting for network switch
> fix: always prompt for network switch

- src/components/Swap/Output.tsx
> fix: remove For in Swap component

- src/components/Swap/Input.tsx
> fix: add background color for swap Input

- src/components/Swap/SwapActionButton/WrapButton.tsx
Wrap should be title- or sentence-cased (I'm not sure which, but in this case they are identical).
> fix: wrap casing

- src/components/Error/ErrorDialog.tsx
> chore: change font style of error

- src/components/Swap/Skeleton.tsx
> feat: update skeleton

- src/components/Swap/Toolbar/Caption.tsx
- src/components/Swap/Toolbar/index.tsx
- Simplifies the Caption implementation to require less bespoke sizing
- Fixes "Connecting...", which was omitted from the displayed states
> fix: captions

- src/components/Swap/Toolbar/Caption.tsx
- src/components/Swap/Toolbar/index.tsx
Fixes a regression where the toolbar height would change during network switching
> fix: retain Toolbar min-height

- src/components/Widget.tsx
- src/hooks/swap/useSwapInfo.tsx
- src/hooks/web3/index.tsx
> feat: allow null provider

- package.json
- src/hooks/useAutoSlippageTolerance.ts
- yarn.lock
copies the logic from interface codebase. this makes sure we have the same gas estimate logic in both.
> fix: upgrade guesstimateGas function

- src/components/Swap/Input.tsx
- src/components/Swap/Summary/index.tsx
- src/cosmos/ControlledSwap.fixture.tsx
- src/cosmos/EventFeed.tsx
- src/cosmos/Swap.fixture.tsx
- src/hooks/swap/index.test.tsx
- src/hooks/swap/index.ts
- src/hooks/swap/useSwapApproval.ts
- src/hooks/swap/useSwapInfo.tsx
- src/index.tsx
- src/state/swap/index.ts
> revert: "feat: add initial analytics handlers"

- .github/workflows/test.yaml
- package.json
- yarn.lock
Prevents duplicate dependencies from entering the lockfile
> test: add deps test

- src/components/Swap/Output.tsx
- src/components/Swap/ReverseButton.tsx
- src/components/Swap/Skeleton.tsx
- src/theme/index.tsx
reverse button was 8px smaller than it should be
> fix: aligned reverse button size w/ figma

- src/cosmos/ControlledSwap.fixture.tsx
- src/cosmos/Swap.fixture.tsx
- src/hooks/useSyncFlags.ts
Prepares the way for permit2 by adding a flag to guard its functionality.
> feat: permit2 flag

- src/components/ActionButton.tsx
- src/components/Swap/SwapActionButton/Permit2Button.tsx
- src/components/Swap/SwapActionButton/SwapButton.tsx
- src/constants/chainInfo.ts
- src/hooks/usePermit2.ts
- src/hooks/usePermitAllowance.ts
- src/hooks/useSyncFlags.ts
- src/hooks/useTokenAllowance.ts
Responses to comments left in #321.
> refactor: permit 2 maintainability improvements

- src/hooks/swap/useWrapCallback.tsx
Prevents the wrap callback from being re-instantiated for new block numbers, which was causing the wrap button to revert to a non-pending state despite a wrap being pending.
Repro:
- Initiate a wrap
- Do not interact with your wallet
- The wrap button _should_ be disabled and say "Confirm in your wallet", but _will_ revert back to an active "Wrap" button.
> fix: decouple wrap callback from balance

- .github/workflows/release.yaml
see the eng plan here: https://www.notion.so/uniswaplabs/Widget-UI-Updates-Eng-Plan-deeec4509ca448b796ed41caf63b2bc3
while the redesign work is ongoing, we'll pause automatic releases.
> feat: disable auto deploys redesign

- src/components/WidgetWrapper.test.tsx
- src/components/WidgetWrapper.tsx
adds max width to the widget container as per the spec 
https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10905%3A109428&t=gY6rvL8clpqdZ5EE-4
> feat: max width for widget

- src/components/TokenSelect/TokenButton.tsx
> fix: output token selector color and height

- src/components/Swap/Skeleton.tsx
Updates the skeleton to match the redesigns for a width of 360px.
> fix: resize skeleton

- src/components/Input.tsx
- src/components/TokenSelect/index.tsx
- src/icons/index.tsx
design spec: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10369%3A107306&t=kN2DYO2XVWBwgUwg-4
update the colors used in the token select dialog, and add a search icon to the search bar
> feat: update colors and icon in token select dialog

- src/components/Input.tsx
- src/components/TokenSelect/CommonBases.test.tsx
- src/components/TokenSelect/CommonBases.tsx
- src/components/TokenSelect/index.tsx
- src/icons/index.tsx
- src/theme/index.tsx
- src/theme/theme.ts
design spec: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10575%3A119214&t=kN2DYO2XVWBwgUwg-4
- adds common tokens to the top of the list in the CurrencySelect dialog
- currently using an existing list of "common bases" - will update to include UNI (to match the spec) in a future PR
> feat: common bases

- src/components/Dialog.tsx
- src/components/Expando.tsx
- src/components/Swap/Settings/RouterPreferenceToggle.tsx
> chore: Use themed text instead of css for Expando headers

- src/assets/svg/spinner.svg
- src/icons/index.tsx
reverts the spinner icon related changes from #360
> fix: revert new spinner icon

- src/hooks/useUniversalRouter.ts
- src/utils/swapErrorToUserReadableMessage.tsx
Updates language around gas estimation errors (see https://github.com/Uniswap/interface/pull/5868).
Adds an error in case the swap is modified in-wallet (see https://github.com/Uniswap/interface/pull/5864).
> fix: swap errors

- src/components/Swap/Settings/TransactionTtlInput.tsx
| Light mode | Dark mode |
| ------------| ---------- |
|<img width="376" alt="image" src="https://user-images.githubusercontent.com/59578595/213508362-9df4e3c1-a407-4893-825f-5f8f7181dfad.png">|<img width="370" alt="image" src="https://user-images.githubusercontent.com/59578595/213508495-15a2d28e-db01-4e55-b3c1-215e84286352.png">|
figma [here](https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10905%3A109583&t=zeOFfprI8BdeEagL-0)
> feat: Update transaction deadline settings UI

- e2e/connect.test.tsx
- src/components/Swap/SwapActionButton/ConnectWalletButton.tsx
fixes the casing of the connect wallet button
> fix: sentence case in connect wallet button

- jest.config.js
- package.json
- src/hooks/usePermitAllowance.test.ts
- src/hooks/usePermitAllowance.ts
- test/setup-jest.ts
- yarn.lock
Use conedison's signTypedData utility for better x-wallet compat.
See https://github.com/Uniswap/interface/pull/5875
> fix: use conedison signTypedData with fallbacks

- src/errors.ts
- src/hooks/swap/useSendSwapTransaction.tsx
- src/hooks/useUniversalRouter.ts
improve default values for dismissable and swap error
> fix: improve swap error

- src/components/Swap/SwapActionButton/index.tsx
- src/components/Swap/index.tsx
hide the "connect wallet" action button when this prop is true
> fix: hide connection UI based on integration prop

- src/components/Dialog.tsx
- src/utils/animations.ts
for useUnmountingAnimation to work, the animations need to be applied to the root of the subtree that is being unmounted
however, the animations need to be applied to the actual visible content that you want to be animated
this solution i landed on, updates `useUnmountingAnimation` to allow the animating element to be different than the unmounting element
> fix: exit animations for dialogs

- src/assets/svg/spinner.svg
- src/icons/index.tsx
change color of center dot, remove the "track" the spinner was moving on (see preview link)
> fix: adjust spinner svg

- src/components/Header.test.tsx
- src/components/Header.tsx
- src/components/Swap/Settings/index.tsx
- src/components/WidgetWrapper.tsx
- src/components/__snapshots__/Header.test.tsx.snap
...and add tests
design file: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10369%3A106894&t=2AxdxplCWk5silOr-0
screenshot:
> fix: adjust spacing in header

- src/components/__snapshots__/Header.test.tsx.snap
- src/hooks/routing/clientSideSmartOrderRouter.ts
fixes the client router to support native tokens identified by their database keys (like "ETH")
> fix: client side router native tokens

- src/components/ActionButton.tsx
- src/components/Swap/Summary/index.test.tsx
- src/components/Swap/Summary/index.tsx
- src/components/__snapshots__/Header.test.tsx.snap
- src/constants/misc.ts
- src/hooks/usePermit2Allowance.ts
Adds a state for when the user has finished approving/signing in their wallet, but the permit tx is still pending
> feat: permit tx pending state

- .github/workflows/release.yaml
remove the manual trigger, re-enable CD
> fix: re-enable cd

- .github/workflows/test.yaml
- src/components/Swap/SwapActionButton/SwapButton.tsx
- src/components/Swap/Toolbar/ToolbarContext.tsx
- src/components/Swap/Toolbar/index.tsx
fixes a circular dependency and adds `yarn build` to the GH "test" action
> fix: circular dependency

- src/components/Error/ErrorBoundary.tsx
- src/components/Swap/Summary/Details.tsx
- src/theme/breakpoints.ts
just audited our font sizes with @infredible  and these are correct (see preview link)
> fix: review responsiveness

- src/components/BottomSheetModal.tsx
- src/components/Dialog.tsx
- src/components/Swap/Summary/index.tsx
- src/components/Swap/SwapActionButton/SwapButton.tsx
- src/components/TokenSelect/TokenOptions.tsx
use the Bottom Sheet for the summary Dialog, if page-centered dialogs are enabled.
> feat: summary dialog bottom sheet

- src/components/Dialog.tsx
- src/components/Swap/Summary/index.tsx
- src/components/TokenSelect/TokenOptions.tsx
- src/cosmos/Swap.fixture.tsx
- src/utils/animations.ts
fixes a bug caused by using `hidden` as a styled component prop, which just hid the element from the page -___-
also fixes an unmounting bug for animationType.NONE
> fix: "hidden" dialog bug 

- src/components/Swap/Toolbar/Caption.tsx
according to design this should be removed
> fix: remove info icon from wrap caption

- src/components/ActionButton.tsx
- src/components/ConnectWallet/ConnectWalletDialog.tsx
- src/components/Dialog.tsx
- src/components/Swap/Input.tsx
- src/components/Swap/Output.tsx
- src/components/Swap/Skeleton.tsx
- src/components/Swap/Toolbar/index.tsx
- src/components/Toggle.tsx
- src/theme/index.tsx
all inner radii should be `1em`, and outer radii should be `1.5em` now
design spec: https://www.figma.com/file/kNSDBMpOzxSTOP6MerohLm/Web-Design-Spec?node-id=10369%3A111843&t=QYhDhsmdTQAL8W17-0
> fix: border radius adjustments

- src/components/Swap/Toolbar/Caption.tsx
- src/components/Swap/Toolbar/index.tsx
these should be vertically aligned
> fix: make sure toolbar contents are aligned

- src/components/Swap/SwapActionButton/index.tsx
- src/components/Swap/Toolbar/index.tsx
reverts #443 because I had a misunderstanding about the design feedback
[see discussion here](https://uniswapteam.slack.com/archives/C04J75E88BE/p1677282332244449)
> fix: revert #443

- src/components/Dialog.tsx
- src/components/TokenSelect/CommonBases.tsx
- src/components/TokenSelect/TokenOptions.tsx
- src/components/TokenSelect/index.tsx
- src/constants/routing.ts
- src/icons/index.tsx
- move X close button to the right side of the header, and make it heavier
- remove side padding from token list section
- adjust font weights, and spacings in the TokenOptions and CommonBases
- add ETH to the common bases for mainnet
- make token selector a bottom sheet on mobile widths
feedbacks here: https://www.notion.so/uniswaplabs/Token-selector-issues-536b091ac80d474c884602e541287e09?pvs=4
> fix: token selector design issues

- src/components/TokenSelect/TokenButton.tsx
> fix: token select button i18n bug

- src/components/Popover.tsx
https://uniswaplabs.atlassian.net/browse/WEB-2757?atlOrigin=eyJpIjoiM2JmOTdhYTI1NjNkNGQ0MWFlNThjMmFkMDU0ZGZjNDMiLCJwIjoiaiJ9
> fix: add default offset to popovers

- .github/dependabot.yml
adds reviewers to the dependabot PRs
> chore: add reviewers to dependabot PRs

- src/components/Swap/SwapActionButton/index.tsx
show "Connect to Ethereum" button when on an unsupported chain
> fix: show connect to ethereum button for unsupported chains

- src/components/Swap/SwapActionButton/SwapButton.tsx
- src/components/Swap/Toolbar/Toolbar.test.tsx
- src/components/TokenSelect/TokenButton.tsx
- src/components/TokenSelect/index.test.tsx
- src/components/TokenSelect/index.tsx
design update - we want the disabled Action Button to say "Select token"
... drop the "a", it's cleaner
> fix: "Select token" button text

- src/state/swap/index.ts
- src/state/swap/settings.ts
> fix: mv settings handlers to settings file

- src/components/ActionButton.tsx
adjust the styling of the action button w/ action to mesh with the new design
> fix: action button action UI

- src/components/Swap/Input.tsx
- src/components/Swap/PriceImpactRow.tsx
- src/components/Swap/Toolbar/ToolbarTradeSummary.tsx
- src/components/Swap/Toolbar/index.tsx
adds text tooltips to the fields in the trade details, and the USD value change %
> feat: add text tooltips to price change and expando fields
